# Generated by Django 5.1.6 on 2025-02-28 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_general', models.BooleanField(default=True, help_text='Access to general content')),
                ('access_christian', models.BooleanField(default=False, help_text='Access to Christian content')),
                ('access_muslim', models.BooleanField(default=False, help_text='Access to Muslim content')),
                ('access_english', models.BooleanField(default=True, help_text='Access to English content')),
                ('access_afrikaans', models.BooleanField(default=False, help_text='Access to Afrikaans content')),
                ('access_xhosa', models.BooleanField(default=False, help_text='Access to Xhosa content')),
                ('access_news_stories', models.BooleanField(default=False, help_text='Access to News Stories')),
                ('access_news_bulletins', models.BooleanField(default=False, help_text='Access to News Bulletins')),
                ('access_sport', models.BooleanField(default=False, help_text='Access to Sport content')),
                ('access_finance', models.BooleanField(default=False, help_text='Access to Finance content')),
                ('access_specialty', models.BooleanField(default=False, help_text='Access to Specialty content')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('SUB_EDITOR', 'Sub Editor'), ('JOURNALIST', 'Journalist'), ('INTERN', 'Intern')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Newskoop Staff'), ('RADIO', 'Radio Station Staff')], default='STAFF', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='radio_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.radiostation'),
        ),
    ]
