# Generated by Django 5.1.6 on 2025-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_radiostation_customuser_is_primary_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiostation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='code',
        ),
        migrations.AddField(
            model_name='radiostation',
            name='province',
            field=models.CharField(choices=[('EASTERN_CAPE', 'Eastern Cape'), ('FREE_STATE', 'Free State'), ('GAUTENG', 'Gauteng'), ('KWAZULU_NATAL', 'KwaZulu-Natal'), ('LIMPOPO', 'Limpopo'), ('MPUMALANGA', 'Mpumalanga'), ('NORTHERN_CAPE', 'Northern Cape'), ('NORTH_WEST', 'North West'), ('WESTERN_CAPE', 'Western Cape'), ('NATIONAL', 'National')], default='GAUTENG', help_text='Province where the radio station is located', max_length=20),
        ),
    ]
