# Generated by Django 5.1.6 on 2025-02-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_radiostation_address_remove_radiostation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiostation',
            name='access_christian',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='access_general',
        ),
        migrations.RemoveField(
            model_name='radiostation',
            name='access_muslim',
        ),
        migrations.AddField(
            model_name='radiostation',
            name='religion_access',
            field=models.CharField(choices=[('GENERAL_ONLY', 'General Only'), ('GENERAL_PLUS_CHRISTIAN', 'General + Christian'), ('GENERAL_PLUS_MUSLIM', 'General + Muslim')], default='GENERAL_ONLY', help_text='Determines if a station gets additional religious content. Options are: General Only, General + Christian, or General + Muslim.', max_length=25),
        ),
    ]
